HAI 1.2

CAN HAS STDIO?
I HAS A FIRST
I HAS A SECOND
GIMMEH FIRST
GIMMEH SECOND
FIRST IS NOW A NUMBR
SECOND IS NOW A NUMBR

DIFFRINT FIRST AN SMALLR OF FIRST AN SECOND
O RLY?
    YA RLY
        VISIBLE "FIRST > SECOND"
    MEBBE BOTH SAEM FIRST AN SECOND
        VISIBLE "FIRST == SECOND"
    NO WAI
        VISIBLE "SECOND > FIRST"
OIC
KTHXBYE
