HAI 1.2
  CAN HAS STDIO?
  I HAS A X ITZ 0
  I HAS A Y ITZ 0
  VISIBLE "Enter first integer value:"
  GIMMEH X
  VISIBLE "Enter second integer value:"
  GIMMEH Y
  VISIBLE "X+Y= " SMOOSH SUM OF X AN Y MKAY
  VISIBLE "X-Y= " SMOOSH DIFF OF X AN Y MKAY
  VISIBLE "X*Y= " SMOOSH PRODUKT OF X AN Y MKAY
  VISIBLE "X/Y= " SMOOSH QUOSHUNT OF X AN Y MKAY
  VISIBLE "X%Y= " SMOOSH MOD OF X AN Y MKAY
KTHXBYE